// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteSelectController from "./autocomplete_select_controller"
application.register("autocomplete-select", AutocompleteSelectController)

import AutosaveController from "./autosave_controller"
application.register("autosave", AutosaveController)

import ColourPickerController from "./colour_picker_controller"
application.register("colour-picker", ColourPickerController)

import CursorController from "./cursor_controller"
application.register("cursor", CursorController)

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import DatatableController from "./datatable_controller"
application.register("datatable", DatatableController)

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import DynamicDescriptionController from "./dynamic_description_controller"
application.register("dynamic-description", DynamicDescriptionController)

import EntityTransactionController from "./entity_transaction_controller"
application.register("entity-transaction", EntityTransactionController)

import FormValidateController from "./form_validate_controller"
application.register("form-validate", FormValidateController)

import IconPickerController from "./icon_picker_controller"
application.register("icon-picker", IconPickerController)

import MaterialTailwindTabController from "./material_tailwind_tab_controller"
application.register("material-tailwind-tab", MaterialTailwindTabController)

import MonthYearSelectorController from "./month_year_selector_controller"
application.register("month-year-selector", MonthYearSelectorController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import PwaInstallationController from "./pwa_installation_controller"
application.register("pwa-installation", PwaInstallationController)

import ReactiveFormController from "./reactive_form_controller"
application.register("reactive-form", ReactiveFormController)

import SelectController from "./select_controller"
application.register("select", SelectController)

import TextAreaAutogrowController from "./text_area_autogrow_controller"
application.register("text-area-autogrow", TextAreaAutogrowController)
