default: &default
  adapter: postgresql
  encoding: unicode

  host: <%= ENV["POSTGRES_HOST"] %>
  database: <%= "#{ENV.fetch("POSTGRES_DATABASE") { 'finance' }}_#{Rails.env}" %>
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
