default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    database: <%= ENV["POSTGRES_DATABASE"] %>_development
  cache:
    <<: *primary_development
    database: app_development_cache
    migrations_paths: db/cache_migrate

test:
  <<: *default
  database: <%= ENV["POSTGRES_DATABASE"] %>_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV["POSTGRES_DATABASE"] %>
  cache:
    <<: *primary_production
    database: app_production_cache
    migrations_paths: db/cache_migrate
