development:
  site:
    name: 30/Fev
    short_name: 30/Fev
    description: A simple way to manage your finances
    keywords: Finance, Budget, Money

test:
  site:
    name: 30/Fev
    short_name: 30/Fev
    description: A simple way to manage your finances
    keywords: Finance, Budget, Money

production:
  site:
    name: 30/Fev
    short_name: 30/Fev
    description: A simple way to manage your finances
    keywords: Finance, Budget, Money
