# frozen_string_literal: true

# Bank Migration
class CreateBanks < ActiveRecord::Migration[8.0]
  def change
    create_table :banks do |t|
      t.string :bank_name, null: false
      t.integer :bank_code, null: false

      t.timestamps
    end

    Bank.create(bank_name: "ACESSO SOLUÇÕES DE PAGAMENTO S.A.", bank_code: 332)
    Bank.create(bank_name: "ADVANCED CORRETORA DE CÂMBIO LTDA", bank_code: 117)
    Bank.create(bank_name: "AGK CORRETORA DE CAMBIO S.A.", bank_code: 272)
    Bank.create(bank_name: "AL5 S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO", bank_code: 349)
    Bank.create(bank_name: "AMAZÔNIA CORRETORA DE CÂMBIO LTDA.", bank_code: 313)
    Bank.create(bank_name: "ATIVA INVESTIMENTOS S.A. CORRETORA DE TÍTULOS, CÂMBIO E VALORES", bank_code: 188)
    Bank.create(bank_name: "AVISTA S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO", bank_code: 280)
    Bank.create(bank_name: "B&T CORRETORA DE CAMBIO LTDA.", bank_code: 80)
    Bank.create(bank_name: "BANCO BARI DE INVESTIMENTOS E FINANCIAMENTOS S.A.", bank_code: 330)
    Bank.create(bank_name: "BANCO BRADESCARD S.A.", bank_code: 63)
    Bank.create(bank_name: "BANCO BTG PACTUAL S.A.", bank_code: 208)
    Bank.create(bank_name: "BANCO CIFRA S.A.", bank_code: 233)
    Bank.create(bank_name: "BANCO DIGIO S.A.", bank_code: 335)
    Bank.create(bank_name: "BANCO FINAXIS S.A.", bank_code: 94)
    Bank.create(bank_name: "BANCO INBURSA S.A.", bank_code: 12)
    Bank.create(bank_name: "BANCO INTER S.A.", bank_code: 77)
    Bank.create(bank_name: "BANCO INVESTCRED UNIBANCO S.A.", bank_code: 249)
    Bank.create(bank_name: "BANCO ITAÚ CONSIGNADO S.A.", bank_code: 29)
    Bank.create(bank_name: "BANCO JOHN DEERE S.A.", bank_code: 217)
    Bank.create(bank_name: "BANCO ORIGINAL S.A.", bank_code: 212)
    Bank.create(bank_name: "BANCO PAN S.A.", bank_code: 623)
    Bank.create(bank_name: "BANCO RANDON S.A.", bank_code: 88)
    Bank.create(bank_name: "BANCO SEMEAR S.A.", bank_code: 743)
    Bank.create(bank_name: "BANCO SISTEMA S.A.", bank_code: 754)
    Bank.create(bank_name: "BANCO TOPÁZIO S.A.", bank_code: 82)
    Bank.create(bank_name: "BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB", bank_code: 756)
    Bank.create(bank_name: "BANCOSEGURO S.A.", bank_code: 81)
    Bank.create(bank_name: "BARI COMPANHIA HIPOTECÁRIA", bank_code: 268)
    Bank.create(bank_name: "BBC LEASING S.A. - ARRENDAMENTO MERCANTIL", bank_code: 378)
    Bank.create(bank_name: "BANCO ABC BRASIL S.A.", bank_code: 246)
    Bank.create(bank_name: "BANCO ABN AMRO S.A.", bank_code: 75)
    Bank.create(bank_name: "BANCO AGIBANK S.A.", bank_code: 121)
    Bank.create(bank_name: "BANCO ALFA S.A.", bank_code: 25)
    Bank.create(bank_name: "BANCO ANDBANK (BRASIL) S.A.", bank_code: 65)
    Bank.create(bank_name: "BANCO ARBI S.A.", bank_code: 213)
    Bank.create(bank_name: "BANCO B3 S.A.", bank_code: 96)
    Bank.create(bank_name: "BANCO BANDEPE S.A.", bank_code: 24)
    Bank.create(bank_name: "BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANTO", bank_code: 21)
    Bank.create(bank_name: "BANCO BRADESCO BBI S.A.", bank_code: 36)
    Bank.create(bank_name: "BANCO BMG S.A.", bank_code: 318)
    Bank.create(bank_name: "BANCO BNP PARIBAS BRASIL S.A.", bank_code: 752)
    Bank.create(bank_name: "BANCO BOCOM BBM S.A.", bank_code: 107)
    Bank.create(bank_name: "BANCO BRADESCO BERJ S.A.", bank_code: 122)
    Bank.create(bank_name: "BANCO BRADESCO FINANCIAMENTOS S.A.", bank_code: 394)
    Bank.create(bank_name: "BANCO BRADESCO S.A.", bank_code: 237)
    Bank.create(bank_name: "BANCO BS2 S.A.", bank_code: 218)
    Bank.create(bank_name: "BANCO C6 CONSIGNADO S.A.", bank_code: 626)
    Bank.create(bank_name: "BANCO C6 S.A.", bank_code: 336)
    Bank.create(bank_name: "BANCO CAIXA GERAL - BRASIL S.A.", bank_code: 473)
    Bank.create(bank_name: "BANCO CAPITAL S.A.", bank_code: 412)
    Bank.create(bank_name: "BANCO CARGILL S.A.", bank_code: 40)
    Bank.create(bank_name: "CHINA CONSTRUCTION BANK (BRASIL) BANCO MÚLTIPLO S/A", bank_code: 320)
    Bank.create(bank_name: "BANCO CEDULA S.A.", bank_code: 266)
    Bank.create(bank_name: "BANCO CETELEM S.A.", bank_code: 739)
    Bank.create(bank_name: "BANCO CITIBANK S.A.", bank_code: 745)
    Bank.create(bank_name: "BANCO CLASSICO S.A.", bank_code: 241)
    Bank.create(bank_name: "BANCO COOPERATIVO SICREDI S.A.", bank_code: 748)
    Bank.create(bank_name: "BANCO CRÉDIT AGRICOLE BRASIL S.A.", bank_code: 222)
    Bank.create(bank_name: "BANCO CREDIT SUISSE (BRASIL) S.A.", bank_code: 505)
    Bank.create(bank_name: "BANCO CREFISA S.A.", bank_code: 69)
    Bank.create(bank_name: "BANCO CSF S.A.", bank_code: 368)
    Bank.create(bank_name: "BANCO DA AMAZONIA S.A.", bank_code: 3)
    Bank.create(bank_name: "BANCO DA CHINA BRASIL S.A.", bank_code: 83)
    Bank.create(bank_name: "BANCO DAYCOVAL S.A.", bank_code: 707)
    Bank.create(bank_name: "BANCO DIGIMAIS S.A.", bank_code: 654)
    Bank.create(bank_name: "BANCO DO BRASIL S.A.", bank_code: 1)
    Bank.create(bank_name: "BANCO DO ESTADO DE SERGIPE S.A.", bank_code: 47)
    Bank.create(bank_name: "BANCO DO ESTADO DO PARÁ S.A.", bank_code: 37)
    Bank.create(bank_name: "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.", bank_code: 41)
    Bank.create(bank_name: "BANCO DO NORDESTE DO BRASIL S.A.", bank_code: 4)
    Bank.create(bank_name: "BANCO FATOR S.A.", bank_code: 265)
    Bank.create(bank_name: "BANCO FIBRA S.A.", bank_code: 224)
    Bank.create(bank_name: "BANCO GM S.A.", bank_code: 390)
    Bank.create(bank_name: "BANCO GUANABARA S.A.", bank_code: 612)
    Bank.create(bank_name: "BANCO HSBC S.A.", bank_code: 269)
    Bank.create(bank_name: "BANCO INDUSTRIAL DO BRASIL S.A.", bank_code: 604)
    Bank.create(bank_name: "BANCO INDUSVAL S.A.", bank_code: 653)
    Bank.create(bank_name: "BANCO ITAÚ BBA S.A.", bank_code: 184)
    Bank.create(bank_name: "BANCO ITAUBANK S.A.", bank_code: 479)
    Bank.create(bank_name: "BANCO J.P. MORGAN S.A.", bank_code: 376)
    Bank.create(bank_name: "BANCO KDB DO BRASIL S.A.", bank_code: 76)
    Bank.create(bank_name: "BANCO KEB HANA DO BRASIL S.A.", bank_code: 757)
    Bank.create(bank_name: "BANCO DE LA NACION ARGENTINA", bank_code: 300)
    Bank.create(bank_name: "BANCO DE LA PROVINCIA DE BUENOS AIRES", bank_code: 495)
    Bank.create(bank_name: "BANCO LUSO BRASILEIRO S.A.", bank_code: 600)
    Bank.create(bank_name: "BANCO MÁXIMA S.A.", bank_code: 243)
    Bank.create(bank_name: "BANCO MERCANTIL DO BRASIL S.A.", bank_code: 389)
    Bank.create(bank_name: "BANCO MERCEDES-BENZ DO BRASIL S.A.", bank_code: 381)
    Bank.create(bank_name: "BANCO MIZUHO DO BRASIL S.A.", bank_code: 370)
    Bank.create(bank_name: "BANCO MODAL S.A.", bank_code: 746)
    Bank.create(bank_name: "BANCO MORGAN STANLEY S.A.", bank_code: 66)
    Bank.create(bank_name: "BANCO MUFG BRASIL S.A.", bank_code: 456)
    Bank.create(bank_name: "BANCO OLÉ CONSIGNADO S.A.", bank_code: 169)
    Bank.create(bank_name: "BANCO ORIGINAL DO AGRONEGÓCIO S.A.", bank_code: 79)
    Bank.create(bank_name: "BANCO OURINVEST S.A.", bank_code: 712)
    Bank.create(bank_name: "BANCO PAULISTA S.A.", bank_code: 611)
    Bank.create(bank_name: "BANCO PINE S.A.", bank_code: 643)
    Bank.create(bank_name: "BANCO RABOBANK INTERNATIONAL BRASIL S.A.", bank_code: 747)
    Bank.create(bank_name: "BANCO RENDIMENTO S.A.", bank_code: 633)
    Bank.create(bank_name: "BANCO RIBEIRAO PRETO S.A.", bank_code: 741)
    Bank.create(bank_name: "BANCO RODOBENS S.A.", bank_code: 120)
    Bank.create(bank_name: "BANCO SAFRA S.A.", bank_code: 422)
    Bank.create(bank_name: "BANCO SANTANDER (BRASIL) S.A.", bank_code: 33)
    Bank.create(bank_name: "BANCO SOCIETE GENERALE BRASIL S.A.", bank_code: 366)
    Bank.create(bank_name: "BANCO SOFISA S.A.", bank_code: 637)
    Bank.create(bank_name: "BANCO SUMITOMO MITSUI BRASILEIRO S.A.", bank_code: 464)
    Bank.create(bank_name: "BANCO TOYOTA DO BRASIL S.A.", bank_code: 387)
    Bank.create(bank_name: "BANCO TRIANGULO S.A.", bank_code: 634)
    Bank.create(bank_name: "BANCO TRICURY S.A.", bank_code: 18)
    Bank.create(bank_name: "BANCO VOLKSWAGEN S.A.", bank_code: 393)
    Bank.create(bank_name: "BANCO VOTORANTIM S.A.", bank_code: 655)
    Bank.create(bank_name: "BANCO VR S.A.", bank_code: 610)
    Bank.create(bank_name: "BANCO WESTERN UNION DO BRASIL S.A.", bank_code: 119)
    Bank.create(bank_name: "BANCO WOORI BANK DO BRASIL S.A.", bank_code: 124)
    Bank.create(bank_name: "BANCO XP S.A.", bank_code: 348)
    Bank.create(bank_name: "BANCO J. SAFRA S.A.", bank_code: 74)
    Bank.create(bank_name: "BCV - BANCO DE CRÉDITO E VAREJO S.A.", bank_code: 250)
    Bank.create(bank_name: "BEXS BANCO DE CÂMBIO S/A", bank_code: 144)
    Bank.create(bank_name: "BEXS CORRETORA DE CÂMBIO S/A", bank_code: 253)
    Bank.create(bank_name: "BGC LIQUIDEZ DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA", bank_code: 134)
    Bank.create(bank_name: "BANCO NACIONAL DE DESENVOLVIMENTO ECONOMICO E SOCIAL", bank_code: 7)
    Bank.create(bank_name: "BNY MELLON BANCO S.A.", bank_code: 17)
    Bank.create(bank_name: "BANK OF AMERICA MERRILL LYNCH BANCO MÚLTIPLO S.A.", bank_code: 755)
    Bank.create(bank_name: "BÔNUSCRED SOCIEDADE DE CRÉDITO DIRETO S.A.", bank_code: 408)
    Bank.create(bank_name: "BPP INSTITUIÇÃO DE PAGAMENTO S.A.", bank_code: 301)
    Bank.create(bank_name: "BR PARTNERS BANCO DE INVESTIMENTO S.A.", bank_code: 126)
    Bank.create(bank_name: "BRB - BANCO DE BRASILIA S.A.", bank_code: 70)
    Bank.create(bank_name: "BRK S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO", bank_code: 92)
    Bank.create(bank_name: "BRL TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", bank_code: 173)
    Bank.create(bank_name: "BROKER BRASIL CORRETORA DE CÂMBIO LTDA.", bank_code: 142)
    Bank.create(bank_name: "BS2 DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", bank_code: 292)
    Bank.create(bank_name: "CREDIT SUISSE HEDGING-GRIFFO CORRETORA DE VALORES S.A", bank_code: 11)
    Bank.create(bank_name: "CAIXA ECONOMICA FEDERAL", bank_code: 104)
    Bank.create(bank_name: "CAMBIONET CORRETORA DE CÂMBIO LTDA.", bank_code: 309)
    Bank.create(bank_name: "CAROL DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.", bank_code: 288)
    Bank.create(bank_name: "CARTOS SOCIEDADE DE CRÉDITO DIRETO S.A.", bank_code: 324)
    Bank.create(bank_name: "CARUANA S.A. - SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO", bank_code: 130)
    Bank.create(bank_name: "CASA DO CRÉDITO S.A. SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR", bank_code: 159)
    Bank.create(bank_name: "CENTRAL DE COOPERATIVAS DE ECONOMIA E CRÉDITO MÚTUO DO ESTADO DO RIO GRANDE DO S", bank_code: 91)
    Bank.create(bank_name: "COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES DE TRÂNSITO DE SANTA CATARINA E RI", bank_code: 16)
    Bank.create(bank_name: "COOPERATIVA DE CRÉDITO RURAL COOPAVEL", bank_code: 281)
    Bank.create(bank_name: "COOPERATIVA DE CRÉDITO RURAL DE ABELARDO LUZ - SULCREDI/CREDILUZ", bank_code: 322)
    Bank.create(bank_name: "COOPERATIVA DE CREDITO RURAL DE IBIAM - SULCREDI/IBIAM", bank_code: 391)
    Bank.create(bank_name: "COOPERATIVA DE CRÉDITO RURAL DE OUROSULCREDI/OURO", bank_code: 286)
    Bank.create(bank_name: "COOPERATIVA DE CREDITO RURAL DE PRIMAVERA DO LESTE", bank_code: 279)
    Bank.create(bank_name: "COOPERATIVA DE CRÉDITO RURAL DE SÃO MIGUEL DO OESTE - SULCREDI/SÃO MIGUEL", bank_code: 273)
    Bank.create(bank_name: "COOPERFORTE - COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS FUNCIONÁRIOS DE INSTIT", bank_code: 379)
    Bank.create(bank_name: "CENTRAL COOPERATIVA DE CRÉDITO NO ESTADO DO ESPÍRITO SANTO - CECOOP", bank_code: 114)
    Bank.create(bank_name: "CIELO S.A.", bank_code: 362)
    Bank.create(bank_name: "CITIBANK N.A.", bank_code: 477)
    Bank.create(bank_name: "CM CAPITAL MARKETS CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS LTDA", bank_code: 180)
    Bank.create(bank_name: "CODEPE CORRETORA DE VALORES E CÂMBIO S.A.", bank_code: 127)
    Bank.create(bank_name: "COMMERZBANK BRASIL S.A. - BANCO MÚLTIPLO", bank_code: 163)
    Bank.create(bank_name: "CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS UNICRED LTDA. - UNICRED DO BRASI", bank_code: 136)
    Bank.create(bank_name: "CONFIDENCE CORRETORA DE CÂMBIO S.A.", bank_code: 60)
    Bank.create(bank_name: "COOPERATIVA CENTRAL DE CRÉDITO - AILOS", bank_code: 85)
    Bank.create(bank_name: "CORA SOCIEDADE DE CRÉDITO DIRETO S.A.", bank_code: 403)
    Bank.create(bank_name: "CREDIALIANÇA COOPERATIVA DE CRÉDITO RURAL", bank_code: 98)
    Bank.create(bank_name: "CREDICOAMO CREDITO RURAL COOPERATIVA", bank_code: 10)
    Bank.create(bank_name: "CREDISAN COOPERATIVA DE CRÉDITO", bank_code: 89)
    Bank.create(bank_name: "CREDISIS - CENTRAL DE COOPERATIVAS DE CRÉDITO LTDA.", bank_code: 97)
    Bank.create(bank_name: "CREDITAS SOCIEDADE DE CRÉDITO DIRETO S.A.", bank_code: 342)
    Bank.create(bank_name: "CREFAZ SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE LT", bank_code: 321)
    Bank.create(bank_name: "COOPERATIVA DE CRÉDITO RURAL DE PEQUENOS AGRICULTORES E DA REFORMA AGRÁRIA DO CE", bank_code: 350)
    Bank.create(bank_name: "CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS DE CRÉDITO E ECONOMIA FAMILIAR E", bank_code: 133)
    Bank.create(bank_name: "DECYSEO CORRETORA DE CAMBIO LTDA.", bank_code: 289)
    Bank.create(bank_name: "DEUTSCHE BANK S.A. - BANCO ALEMAO", bank_code: 487)
    Bank.create(bank_name: "EASYNVEST - TÍTULO CORRETORA DE VALORES SA", bank_code: 140)
    Bank.create(bank_name: "FACTA FINANCEIRA S.A. - CRÉDITO FINANCIAMENTO E INVESTIMENTO", bank_code: 149)
    Bank.create(bank_name: "FAIR CORRETORA DE CAMBIO S.A.", bank_code: 196)
    Bank.create(bank_name: "FFA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.", bank_code: 343)
    Bank.create(bank_name: "FIDÚCIA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE L", bank_code: 382)
    Bank.create(bank_name: "FRAM CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", bank_code: 331)
    Bank.create(bank_name: "FRENTE CORRETORA DE CÂMBIO LTDA.", bank_code: 285)
    Bank.create(bank_name: "GENIAL INVESTIMENTOS CORRETORA DE VALORES MOBILIÁRIOS S.A.", bank_code: 278)
    Bank.create(bank_name: "GERENCIANET S.A.", bank_code: 364)
    Bank.create(bank_name: "GET MONEY CORRETORA DE CÂMBIO S.A.", bank_code: 138)
    Bank.create(bank_name: "GLOBAL FINANÇAS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO", bank_code: 384)
    Bank.create(bank_name: "GOLDMAN SACHS DO BRASIL BANCO MULTIPLO S.A.", bank_code: 64)
    Bank.create(bank_name: "GUIDE INVESTIMENTOS S.A. CORRETORA DE VALORES", bank_code: 177)
    Bank.create(bank_name: "GUITTA CORRETORA DE CAMBIO LTDA.", bank_code: 146)
    Bank.create(bank_name: "HAITONG BANCO DE INVESTIMENTO DO BRASIL S.A.", bank_code: 78)
    Bank.create(bank_name: "HIPERCARD BANCO MÚLTIPLO S.A.", bank_code: 62)
    Bank.create(bank_name: "HS FINANCEIRA S/A CREDITO, FINANCIAMENTO E INVESTIMENTOS", bank_code: 189)
    Bank.create(bank_name: "HUB PAGAMENTOS S.A", bank_code: 396)
    Bank.create(bank_name: "IB CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS S.A.", bank_code: 271)
    Bank.create(bank_name: "ICAP DO BRASIL CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", bank_code: 157)
    Bank.create(bank_name: "ICBC DO BRASIL BANCO MÚLTIPLO S.A.", bank_code: 132)
    Bank.create(bank_name: "ING BANK N.V.", bank_code: 492)
    Bank.create(bank_name: "INTESA SANPAOLO BRASIL S.A. - BANCO MÚLTIPLO", bank_code: 139)
    Bank.create(bank_name: "ITAÚ UNIBANCO HOLDING S.A.", bank_code: 652)
    Bank.create(bank_name: "ITAÚ UNIBANCO S.A.", bank_code: 341)
    Bank.create(bank_name: "JPMORGAN CHASE BANK, NATIONAL ASSOCIATION", bank_code: 488)
    Bank.create(bank_name: "BOLETOBANCÁRIO.COM TECNOLOGIA DE PAGAMENTOS LTDA.", bank_code: 383)
    Bank.create(bank_name: "KIRTON BANK S.A. - BANCO MÚLTIPLO", bank_code: 399)
    Bank.create(bank_name: "LASTRO RDV DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", bank_code: 293)
    Bank.create(bank_name: "LECCA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A", bank_code: 105)
    Bank.create(bank_name: "LEVYCAM - CORRETORA DE CAMBIO E VALORES LTDA.", bank_code: 145)
    Bank.create(bank_name: "LISTO SOCIEDADE DE CREDITO DIRETO S.A.", bank_code: 397)
    Bank.create(bank_name: "MAGLIANO S.A. CORRETORA DE CAMBIO E VALORES MOBILIARIOS", bank_code: 113)
    Bank.create(bank_name: "MERCADOPAGO.COM REPRESENTACOES LTDA.", bank_code: 323)
    Bank.create(bank_name: "MONEY PLUS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORT", bank_code: 274)
    Bank.create(bank_name: "MONEYCORP BANCO DE CÂMBIO S.A.", bank_code: 259)
    Bank.create(bank_name: "MS BANK S.A. BANCO DE CÂMBIO", bank_code: 128)
    Bank.create(bank_name: "MS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA", bank_code: 377)
    Bank.create(bank_name: "NECTON INVESTIMENTOS S.A. CORRETORA DE VALORES MOBILIÁRIOS E COMMODITIES", bank_code: 354)
    Bank.create(bank_name: "NOVA FUTURA CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", bank_code: 191)
    Bank.create(bank_name: "NOVO BANCO CONTINENTAL S.A. - BANCO MÚLTIPLO", bank_code: 753)
    Bank.create(bank_name: "NU PAGAMENTOS S.A.", bank_code: 260)
    Bank.create(bank_name: "OLIVEIRA TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIARIOS S.A.", bank_code: 111)
    Bank.create(bank_name: "OM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA", bank_code: 319)
    Bank.create(bank_name: "OMNI BANCO S.A.", bank_code: 613)
    Bank.create(bank_name: "ÓRAMA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", bank_code: 325)
    Bank.create(bank_name: "ÓTIMO SOCIEDADE DE CRÉDITO DIRETO S.A.", bank_code: 355)
    Bank.create(bank_name: "PAGSEGURO INTERNET S.A.", bank_code: 290)
    Bank.create(bank_name: "PARANÁ BANCO S.A.", bank_code: 254)
    Bank.create(bank_name: "PARATI - CREDITO, FINANCIAMENTO E INVESTIMENTO S.A.", bank_code: 326)
    Bank.create(bank_name: "PARMETAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA", bank_code: 194)
    Bank.create(bank_name: "PEFISA S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO", bank_code: 174)
    Bank.create(bank_name: "PI DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", bank_code: 315)
    Bank.create(bank_name: "PICPAY SERVICOS S.A.", bank_code: 380)
    Bank.create(bank_name: "PLANNER CORRETORA DE VALORES S.A.", bank_code: 100)
    Bank.create(bank_name: "PLURAL S.A. BANCO MÚLTIPLO", bank_code: 125)
    Bank.create(bank_name: "PÓLOCREDSOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORT", bank_code: 93)
    Bank.create(bank_name: "PORTOCRED S.A. - CREDITO, FINANCIAMENTO E INVESTIMENTO", bank_code: 108)
    Bank.create(bank_name: "PORTOPAR DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.", bank_code: 306)
    Bank.create(bank_name: "QI SOCIEDADE DE CRÉDITO DIRETO S.A.", bank_code: 329)
    Bank.create(bank_name: "RB CAPITAL INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LIMITADA", bank_code: 283)
    Bank.create(bank_name: "REALIZE CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.", bank_code: 374)
    Bank.create(bank_name: "RENASCENCA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA", bank_code: 101)
    Bank.create(bank_name: "SAGITUR CORRETORA DE CÂMBIO LTDA.", bank_code: 270)
    Bank.create(bank_name: "SCOTIABANK BRASIL S.A. BANCO MÚLTIPLO", bank_code: 751)
    Bank.create(bank_name: "SENFF S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO", bank_code: 276)
    Bank.create(bank_name: "SENSO CORRETORA DE CAMBIO E VALORES MOBILIARIOS S.A", bank_code: 545)
    Bank.create(bank_name: "SERVICOOP - COOPERATIVA DE CRÉDITO DOS SERVIDORES PÚBLICOS ESTADUAIS DO RIO GRAN", bank_code: 190)
    Bank.create(bank_name: "BANCO SMARTBANK S.A.", bank_code: 630)
    Bank.create(bank_name: "SOCOPA SOCIEDADE CORRETORA PAULISTA S.A.", bank_code: 363)
    Bank.create(bank_name: "SOCRED S.A. - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO P", bank_code: 183)
    Bank.create(bank_name: "SOLIDUS S.A. CORRETORA DE CAMBIO E VALORES MOBILIARIOS", bank_code: 365)
    Bank.create(bank_name: "SOROCREDCRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.", bank_code: 299)
    Bank.create(bank_name: "STATE STREET BRASIL S.A. ? BANCO COMERCIAL", bank_code: 14)
    Bank.create(bank_name: "STONE PAGAMENTOS S.A.", bank_code: 197)
    Bank.create(bank_name: "SUMUP SOCIEDADE DE CRÉDITO DIRETO S.A.", bank_code: 404)
    Bank.create(bank_name: "SUPER PAGAMENTOS E ADMINISTRAÇÃO DE MEIOS ELETRÔNICOS S.A.", bank_code: 340)
    Bank.create(bank_name: "TERRA INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.", bank_code: 307)
    Bank.create(bank_name: "TORO CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA", bank_code: 352)
    Bank.create(bank_name: "TRAVELEX BANCO DE CÂMBIO S.A.", bank_code: 95)
    Bank.create(bank_name: "TREVISO CORRETORA DE CÂMBIO S.A.", bank_code: 143)
    Bank.create(bank_name: "TRINUS CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", bank_code: 360)
    Bank.create(bank_name: "TULLETT PREBON BRASIL CORRETORA DE VALORES E CÂMBIO LTDA", bank_code: 131)
    Bank.create(bank_name: "UBS BRASIL BANCO DE INVESTIMENTO S.A.", bank_code: 129)
    Bank.create(bank_name: "UBS BRASIL CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS S.A.", bank_code: 15)
    Bank.create(bank_name: "UNIPRIME CENTRAL - CENTRAL INTERESTADUAL DE COOPERATIVAS DE CREDITO LTDA.", bank_code: 99)
    Bank.create(bank_name: "UNIPRIME NORTE DO PARANÁ - COOPERATIVA DE CRÉDITO LTDA", bank_code: 84)
    Bank.create(bank_name: "UP.P SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.", bank_code: 373)
    Bank.create(bank_name: "VIP'S CORRETORA DE CÂMBIO LTDA.", bank_code: 298)
    Bank.create(bank_name: "VISION S.A. CORRETORA DE CAMBIO", bank_code: 296)
    Bank.create(bank_name: "VITREO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.", bank_code: 367)
    Bank.create(bank_name: "VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.", bank_code: 310)
    Bank.create(bank_name: "WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMBIO LTDA.", bank_code: 371)
    Bank.create(bank_name: "XP INVESTIMENTOS CORRETORA DE CÂMBIO,TÍTULOS E VALORES MOBILIÁRIOS S/A", bank_code: 102)
    Bank.create(bank_name: "ZEMA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A", bank_code: 359)
    Bank.create(bank_name: "PIX", bank_code: 0)
  end
end
