# frozen_string_literal: true

# == Schema Information
#
# Table name: banks
#
#  id         :integer          not null, primary key
#  bank_name  :string           not null
#  bank_code  :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Bank < ApplicationRecord
  # @extends ..................................................................
  # @includes .................................................................
  # @security (i.e. attr_accessible) ..........................................
  # @relationships ............................................................
  has_many :cards
  has_many :user_bank_accounts

  # @validations ..............................................................
  validates :bank_name, :bank_code, presence: true

  # @callbacks ................................................................
  # @scopes ...................................................................
  # @additional_config ........................................................
  # @class_methods ............................................................
  # @public_instance_methods ..................................................
  # @protected_instance_methods ...............................................
  # @private_instance_methods .................................................
end
