# frozen_string_literal: true

class Bank < ApplicationRecord
  # @extends ..................................................................
  # @includes .................................................................
  # @security (i.e. attr_accessible) ..........................................
  # @relationships ............................................................
  has_many :cards
  has_many :user_bank_accounts

  # @validations ..............................................................
  validates :bank_name, :bank_code, presence: true
  validates :bank_name, uniqueness: { scope: :bank_code }

  # @callbacks ................................................................
  # @scopes ...................................................................
  # @additional_config ........................................................
  # @class_methods ............................................................
  # @public_instance_methods ..................................................
  # @protected_instance_methods ...............................................
  # @private_instance_methods .................................................
end

# == Schema Information
#
# Table name: banks
#
#  id         :bigint           not null, primary key
#  bank_code  :string           not null
#  bank_name  :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
