# frozen_string_literal: true

# == Schema Information
#
# Table name: installments
#
#  id               :bigint           not null, primary key
#  price            :decimal(10, 2)   default(0.0), not null
#  number           :integer          default(1), not null
#  paid             :boolean          default(FALSE), not null
#  installable_type :string           not null
#  installable_id   :bigint           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Installment < ApplicationRecord
  # @extends ..................................................................
  # @includes .................................................................
  # @security (i.e. attr_accessible) ..........................................
  # @relationships ............................................................
  belongs_to :installable, polymorphic: true

  # @validations ..............................................................
  validates :price, :number, presence: true
  validates :paid, inclusion: { in: [ true, false ] }

  # @callbacks ................................................................
  # @scopes ...................................................................
  # @additional_config ........................................................
  # @class_methods ............................................................
  # @public_instance_methods ..................................................
  # @protected_instance_methods ...............................................
  # @private_instance_methods .................................................
end
